const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    swagger: "2.0",
    version: "1.0.0",
    title: "Build Api Documentation",
    description:
      "Build Api Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "User",
      description: "User data post, get, update , delete",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "X-API-KEY", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    User: {
      name: "string",
      phone: "string",
      email: "string",
      image: "string",
    },
    AddUser: {
      name: "string",
      phone: "string",
      email: "string",
      image: "string",
    },
  },
};

const outputFile = "./swagger-outputfile.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app"); // Your project's root file
});
